### ISSUE TITLE
Target .NET Standard 2.0 instead of .NET Core

### ISSUE THREAD

**Issue by danieltharris** [GreyManSoftware/JlrSharp#6]
Was there a specific reason to target .NET Core? 

Have you thought about targeting .NET Standard 2.0 instead? This would increase compatibility of the library.  I tried this out myself by moving the files into a .NET Standard class library and it worked fine for me.

Are you looking for any contributors to expand the library to cover the last few endpoints?

**Comment by GreyManSoftware** [comment]
Howdy! Thanks for raising the issue. The only reason I specifically targeted .NetCore was because I use the library in a Azure Function, to power my Alexa Jaguar Remote skill. I did a quick look and it seems if I take a dependency on System.Text.Json, it does seem to at least compile! :)

I'll do some quick tests and ensure it works and release a new package (1.0.3) that will allow you to target .NetCore or .NetStandard.

Finally, as for dev effort yes please! If you've got some spare time to finish off features and what not, I would be immensely grateful. Just fork her up and stick a pull request in when you are ready. Any questions at all, just let me know. Happy to chat off Git too if that's better :)

**Comment by GreyManSoftware** [comment]
So I gave it a quick look over and had a few issues even debugging with .NetStandard2.0! I can't even seem to get it to hit a breakpoint. If you want to make a change to get it working for both NetCore and NetStandard I would really appreciate it!
